version: 0.0
os: linux
files:
  - source: quizspark-backend.tar.gz
    destination: /home/ubuntu
  - source: before_install.sh
    destination: /home/ubuntu
  - source: after_install.sh
    destination: /home/ubuntu
  - source: start.sh
    destination: /home/ubuntu
permissions:
  - object: /home/ubuntu
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  BeforeInstall:
    - location: before_install.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: after_install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: start.sh
      timeout: 300
      runas: ubuntu 