name: Deploy Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0' # Weekly scan

env:
  AWS_REGION: ap-south-1
  EC2_IP: ec2-3-110-27-110.ap-south-1.compute.amazonaws.com
  EC2_IP_NUMERIC: 3.110.27.110
  DNS: quizspark.s3-website.ap-south-1.amazonaws.com
  ECR_REPOSITORY: quizspark
  S3_BUCKET: quizspark

jobs:
  codeql-analysis:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}
        queries: security-and-quality
        config: |
          name: "Enhanced Security Configuration"
          disable-default-queries: false
          paths:
            - src/
            - server/
            - public/
          paths-ignore:
            - node_modules/
            - dist/
            - .git/
            - .github/
          query-filters:
            - exclude:
                problem.severity: warning
            - include:
                problem.severity: error
            - include:
                problem.severity: critical
          security-severity:
            - critical
            - high
            - medium
          security-categories:
            - injection
            - authentication
            - authorization
            - cryptography
            - data-exposure
            - deserialization
            - xss
            - csrf
            - sql-injection
            - command-injection

    - name: Autobuild
      uses: github/codeql-action/autobuild@v3

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:${{matrix.language}}"

    - name: Security Checks
      run: |
        # Update critical dependencies
        npm install react-router@latest react-router-dom@latest
        npm install vite@latest
        
        # Run security checks
        echo "Running npm audit..."
        npm audit || true
        
        echo "Running npm audit fix..."
        npm audit fix || true
        
        echo "Checking for outdated packages..."
        npm outdated || true
        
        echo "Security checks completed"

  deploy-backend:
    needs: codeql-analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ env.EC2_IP }} >> ~/.ssh/known_hosts
          ls -la ~/.ssh/
          cat ~/.ssh/id_ed25519

      - name: Create ECR repository
        run: |
          aws ecr describe-repositories --repository-names ${{ env.ECR_REPOSITORY }} || \
          aws ecr create-repository --repository-name ${{ env.ECR_REPOSITORY }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no ubuntu@${{ env.EC2_IP }} << EOF
            # Set environment variables
            export AWS_REGION=${{ env.AWS_REGION }}
            export ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
            export ECR_REPOSITORY=${{ env.ECR_REPOSITORY }}
            export GITHUB_SHA=${{ github.sha }}
            
            # Login to ECR
            aws ecr get-login-password --region \${AWS_REGION} | docker login --username AWS --password-stdin \${ECR_REGISTRY}
            
            # Pull the latest image
            docker pull \${ECR_REGISTRY}/\${ECR_REPOSITORY}:\${GITHUB_SHA}
            
            # Check if container exists
            if docker ps -a | grep -q quizspark-backend; then
              echo "Container exists, updating..."
              # Stop and remove existing container
              docker stop quizspark-backend || true
              docker rm quizspark-backend || true
            else
              echo "Container does not exist, creating new one..."
            fi
            
            # Start container with new image
            docker run -d \
              --name quizspark-backend \
              -p 3000:3000 \
              -e NODE_ENV=production \
              --restart unless-stopped \
              \${ECR_REGISTRY}/\${ECR_REPOSITORY}:\${GITHUB_SHA}
            
            # Verify container is running
            echo "Verifying container status..."
            sleep 5
            if docker ps | grep -q quizspark-backend; then
              echo "Container started successfully"
            else
              echo "Container failed to start"
              docker logs quizspark-backend || true
              exit 1
            fi
          EOF

  deploy-frontend:
    needs: deploy-backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to S3
        run: |
          aws s3 sync dist/ s3://${{ env.S3_BUCKET }}/
          aws s3 website s3://${{ env.S3_BUCKET }} --index-document index.html --error-document index.html

  setup-monitoring:
    needs: [deploy-backend, deploy-frontend]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ env.EC2_IP }} >> ~/.ssh/known_hosts
          ls -la ~/.ssh/
          cat ~/.ssh/id_ed25519

      - name: Create monitoring configs
        run: |
          # Create monitoring directory
          mkdir -p monitoring

          # Create Prometheus config
          cat > monitoring/prometheus.yml << EOF
          global:
            scrape_interval: 15s
            evaluation_interval: 15s
            retention: 30d
            scrape_timeout: 10s

          rule_files:
            - 'alert.rules'
            - 'recording.rules'

          scrape_configs:
            - job_name: 'quizspark-backend'
              static_configs:
                - targets: ['${{ env.EC2_IP_NUMERIC }}:3000']
              metrics_path: '/metrics'
              scrape_interval: 10s
              scheme: https
              tls_config:
                cert_file: /etc/prometheus/certs/cert.pem
                key_file: /etc/prometheus/certs/key.pem
              basic_auth:
                username: prometheus
                password: ${PROMETHEUS_PASSWORD}

            - job_name: 'node-exporter'
              static_configs:
                - targets: ['${{ env.EC2_IP_NUMERIC }}:9100']
              scrape_interval: 15s
              scheme: https
              tls_config:
                cert_file: /etc/prometheus/certs/cert.pem
                key_file: /etc/prometheus/certs/key.pem

            - job_name: 'prometheus'
              static_configs:
                - targets: ['${{ env.EC2_IP_NUMERIC }}:9090']
              scrape_interval: 15s
              scheme: https
              tls_config:
                cert_file: /etc/prometheus/certs/cert.pem
                key_file: /etc/prometheus/certs/key.pem

            - job_name: 'blackbox'
              metrics_path: /probe
              params:
                module: [http_2xx]
              static_configs:
                - targets:
                  - https://quizspark.s3-website.ap-south-1.amazonaws.com
                  - https://${{ env.EC2_IP_NUMERIC }}:3000
              relabel_configs:
                - source_labels: [__address__]
                  target_label: __param_target
                - source_labels: [__param_target]
                  target_label: instance
                - target_label: __address__
                  replacement: ${{ env.EC2_IP_NUMERIC }}:9115
          EOF

          # Create recording rules
          cat > monitoring/recording.rules << EOF
          groups:
            - name: recording_rules
              rules:
                # System Metrics
                - record: instance:node_cpu_utilization:rate5m
                  expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)

                - record: instance:node_memory_utilization:ratio
                  expr: (1 - ((node_memory_MemAvailable_bytes or node_memory_Buffers_bytes + node_memory_Cached_bytes + node_memory_MemFree_bytes) / node_memory_MemTotal_bytes)) * 100

                - record: instance:node_disk_utilization:ratio
                  expr: (1 - (node_filesystem_avail_bytes / node_filesystem_size_bytes)) * 100

                # Application Metrics
                - record: http_request_duration_seconds:rate5m
                  expr: rate(http_request_duration_seconds_sum[5m]) / rate(http_request_duration_seconds_count[5m])

                - record: http_requests_total:rate5m
                  expr: rate(http_requests_total[5m])

                - record: http_errors_total:rate5m
                  expr: rate(http_requests_total{status=~"5.."}[5m])

                # Security Metrics
                - record: auth_failed_attempts:rate5m
                  expr: rate(auth_failed_attempts_total[5m])

                - record: auth_unauthorized_requests:rate5m
                  expr: rate(auth_unauthorized_requests_total[5m])

                # Database Metrics
                - record: db_query_duration_seconds:rate5m
                  expr: rate(db_query_duration_seconds_sum[5m]) / rate(db_query_duration_seconds_count[5m])

                - record: db_queries_total:rate5m
                  expr: rate(db_queries_total[5m])

                # Performance Metrics
                - record: application_latency_seconds:quantile95
                  expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))

                - record: database_latency_seconds:quantile95
                  expr: histogram_quantile(0.95, sum(rate(db_query_duration_seconds_bucket[5m])) by (le))
          EOF

      - name: Deploy monitoring stack
        run: |
          # SSH into EC2 and setup monitoring
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no ubuntu@${{ env.EC2_IP }} '
            # Stop any existing containers
            docker-compose -f ~/monitoring/docker-compose.yml down || true

            # Install Docker Compose if not present
            sudo apt-get update
            sudo apt-get install -y docker-compose

            # Create monitoring directory
            mkdir -p ~/monitoring

            # Create docker-compose.yml for monitoring stack
            cat > ~/monitoring/docker-compose.yml << "EOL"
            version: "3"
            services:
              prometheus:
                image: prom/prometheus:latest
                ports:
                  - "9090:9090"
                volumes:
                  - ./prometheus.yml:/etc/prometheus/prometheus.yml
                  - ./recording.rules:/etc/prometheus/recording.rules
                  - prometheus-data:/prometheus
                command:
                  - "--config.file=/etc/prometheus/prometheus.yml"
                  - "--storage.tsdb.path=/prometheus"
                  - "--storage.tsdb.retention.time=30d"
                restart: always
                network_mode: "host"

              node-exporter:
                image: prom/node-exporter:latest
                ports:
                  - "9100:9100"
                restart: always
                network_mode: "host"

              blackbox-exporter:
                image: prom/blackbox-exporter:latest
                ports:
                  - "9115:9115"
                restart: always
                network_mode: "host"

            volumes:
              prometheus-data:
            EOL

            # Copy monitoring configs
            scp -i ~/.ssh/id_ed25519 monitoring/prometheus.yml ubuntu@${{ env.EC2_IP }}:~/monitoring/
            scp -i ~/.ssh/id_ed25519 monitoring/recording.rules ubuntu@${{ env.EC2_IP }}:~/monitoring/

            # Start monitoring stack
            cd ~/monitoring
            docker-compose up -d

            # Wait for services to start
            sleep 30

            # Check if services are running
            docker ps
            curl -f https://${{ env.EC2_IP_NUMERIC }}:9090/-/healthy
            curl -f https://${{ env.EC2_IP_NUMERIC }}:9100/metrics
            curl -f https://${{ env.EC2_IP_NUMERIC }}:9115/metrics
          '

      - name: Verify monitoring setup
        run: |
          sleep 60
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no ubuntu@${{ env.EC2_IP }} '
            # Fix dpkg error
            sudo dpkg --configure -a
            
            # List all containers to see their names
            echo "All running containers:"
            docker ps -a
            
            # Check if ports are open using ss
            sudo apt-get update
            sudo apt-get install -y iproute2
            sudo ss -tulpn | grep 9090
            sudo ss -tulpn | grep 9100
            sudo ss -tulpn | grep 9115
            
            # Check service logs using the first container that matches the pattern
            PROMETHEUS_CONTAINER=$(docker ps -a | grep prometheus | head -n 1 | awk "{print \$1}")
            NODE_EXPORTER_CONTAINER=$(docker ps -a | grep node-exporter | head -n 1 | awk "{print \$1}")
            BLACKBOX_CONTAINER=$(docker ps -a | grep blackbox-exporter | head -n 1 | awk "{print \$1}")
            
            if [ ! -z "$PROMETHEUS_CONTAINER" ]; then
              echo "Prometheus logs:"
              docker logs $PROMETHEUS_CONTAINER
            else
              echo "No Prometheus container found"
            fi
          '

        


        