name: Full Stack Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AWS_REGION: ap-south-1
  EC2_IP: "13.127.72.180"
  EC2_DNS: "ec2-13-127-72-180.ap-south-1.compute.amazonaws.com"
  ECR_REPOSITORY: "quizspark-backend"
  S3_BUCKET: "quizspark-frontend"

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_ENV

    - name: Deploy to EC2
      run: |
        # Create SSH key from secret
        printf "%s\n" "${{ secrets.EC2_SSH_KEY }}" > key.pem
        chmod 600 key.pem
        if [ ! -s key.pem ]; then
          echo "Error: SSH key file is empty or not created"
          exit 1
        fi

        # SSH into EC2 and run deployment commands
        ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${{ env.EC2_IP }} << EOF
          # Login to ECR
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin ${{ steps.login-ecr.outputs.registry }}
          
          # Stop and remove existing container
          docker stop quizspark-backend || true
          docker rm quizspark-backend || true
          
          # Remove existing image
          docker rmi quizspark-backend || true
          
          # Pull and run new image
          docker pull ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
          docker run -d \
            --name quizspark-backend \
            --restart unless-stopped \
            -p 3000:3000 \
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
          
          # Wait for container to start
          sleep 10
          
          # Verify container is running
          if ! docker ps | grep -q quizspark-backend; then
            echo "Error: Container failed to start"
            docker logs quizspark-backend
            exit 1
          fi
          
          # Check container logs
          echo "Container logs:"
          docker logs quizspark-backend
        EOF
        
        # Clean up local files
        rm -f key.pem

    - name: Verify Backend Deployment
      run: |
        sleep 10
        response=$(curl -s -o /dev/null -w "%{http_code}" http://${{ env.EC2_DNS }}:3000/api/upcoming-quizzes/1)
        if [ "$response" != "200" ]; then
          echo "Error: Backend is not responding correctly"
          exit 1
        fi

    - name: Output Backend URL
      run: |
        echo "Backend deployed at: http://${{ env.EC2_DNS }}:3000"

  deploy-frontend:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Clean S3 Bucket
      run: |
        aws s3 rm s3://${{ env.S3_BUCKET }} --recursive

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Clean frontend directory
      working-directory: frontend
      run: |
        rm -rf node_modules
        rm -rf dist
        rm -f package-lock.json

    - name: Install dependencies
      working-directory: frontend
      run: npm install

    - name: Build
      working-directory: frontend
      run: npm run build

    - name: Deploy to S3
      run: |
        aws s3 sync frontend/dist s3://${{ env.S3_BUCKET }} --delete
        aws s3 cp frontend/dist/index.html s3://${{ env.S3_BUCKET }}/index.html --cache-control "no-cache, no-store, must-revalidate"
        aws s3 cp frontend/dist/assets s3://${{ env.S3_BUCKET }}/assets --recursive --cache-control "max-age=31536000"

    - name: Verify Frontend Deployment
      run: |
        sleep 5
        response=$(curl -s -o /dev/null -w "%{http_code}" https://${{ env.S3_BUCKET }}.s3-website.${{ env.AWS_REGION }}.amazonaws.com)
        if [ "$response" != "200" ]; then
          echo "Error: Frontend is not responding correctly"
          exit 1
        fi

    - name: Output Frontend URL
      run: |
        echo "Frontend deployed at: https://${{ env.S3_BUCKET }}.s3-website.${{ env.AWS_REGION }}.amazonaws.com"

        